# Generated by Django 5.2.10 on 2026-01-25 20:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objednavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo_objednavky', models.CharField(max_length=50, unique=True, verbose_name='Číslo objednávky')),
                ('zakaznik', models.CharField(max_length=100, verbose_name='Zákazník')),
                ('mnozstvo', models.IntegerField(verbose_name='Množstvo (ks)')),
                ('datum_zadania', models.DateField(default=django.utils.timezone.now, verbose_name='Dátum zadania')),
                ('datum_pozadovane', models.DateField(verbose_name='Požadovaný termín')),
                ('stav', models.CharField(choices=[('nova', '🆕 Nová'), ('vyroba', '⚙️ Vo výrobe'), ('hotovo', '✅ Hotovo'), ('pozastavene', '⏸️ Pozastavené')], default='nova', max_length=20, verbose_name='Stav')),
                ('poznamka', models.TextField(blank=True, verbose_name='Poznámka')),
            ],
            options={
                'verbose_name': 'Objednávka',
                'verbose_name_plural': 'Objednávky',
                'ordering': ['datum_pozadovane'],
            },
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=200, verbose_name='Názov produktu')),
                ('cislo_dielu', models.CharField(max_length=50, unique=True, verbose_name='Číslo dielu')),
                ('cislo_vykresu', models.CharField(blank=True, max_length=50, null=True, verbose_name='Číslo výkresu')),
                ('index', models.IntegerField(default=0, verbose_name='Index zmeny')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='Materiál (napr. Ocel 11373)')),
                ('rozmer_polotovaru', models.CharField(blank=True, max_length=100, verbose_name='Rozmer polotovaru')),
                ('spotreba_ks', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Spotreba na kus')),
                ('cas_vyroby', models.IntegerField(default=0, verbose_name='Čas výroby (min)')),
                ('norma_hod', models.IntegerField(default=0, verbose_name='Norma (ks/hod)')),
                ('vykres_pdf', models.FileField(blank=True, null=True, upload_to='vykresy/', verbose_name='Výkres (PDF)')),
                ('baliaci_predpis_pdf', models.FileField(blank=True, null=True, upload_to='baliace_predpisy/', verbose_name='Baliaci predpis (PDF)')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
            },
        ),
        migrations.CreateModel(
            name='Stroj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=100, verbose_name='Názov stroja')),
                ('typ', models.CharField(blank=True, max_length=100, verbose_name='Typ/Model')),
                ('status', models.CharField(choices=[('OK', '🟢 Funkčný'), ('PORUCHA', '🔴 Porucha'), ('SERVIS', '🟡 V servise')], default='OK', max_length=10, verbose_name='Aktuálny stav')),
                ('hodinova_sadzba', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Cena za hodinu (€)')),
                ('datum_posledneho_servisu', models.DateField(blank=True, null=True, verbose_name='Posledný servis')),
                ('manual_pdf', models.FileField(blank=True, null=True, upload_to='manualy_strojov/', verbose_name='Manuál (PDF)')),
            ],
        ),
        migrations.CreateModel(
            name='KontrolaKvality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cas_kontroly', models.DateTimeField(auto_now_add=True)),
                ('namerana_hodnota', models.CharField(max_length=50, verbose_name='Nameraná hodnota')),
                ('vysledok_ok', models.BooleanField(default=True, verbose_name='Je to OK?')),
                ('fotka', models.ImageField(blank=True, null=True, upload_to='kontrola_kvality/', verbose_name='Fotka produktu')),
                ('poznamka', models.TextField(blank=True, verbose_name='Poznámka ku kontrole')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('objednavka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontroly', to='core.objednavka')),
            ],
        ),
        migrations.CreateModel(
            name='HlasenieVyroby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cas_hlasenia', models.DateTimeField(auto_now_add=True)),
                ('typ_problemu', models.CharField(choices=[('NEPODAROK', '🗑️ Nepodarok (Scrap)'), ('PORUCHA_STROJA', '⚙️ Porucha stroja'), ('POSKODENY_NASTROJ', '🔧 Poškodený nástroj'), ('INA_CHYBA', '⚠️ Iný problém')], max_length=20)),
                ('pocet_kusov_nepodarkov', models.PositiveIntegerField(default=0, verbose_name='Počet zlých kusov')),
                ('popis_problemu', models.TextField(verbose_name='Popis problému')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('objednavka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hlasenia', to='core.objednavka')),
            ],
        ),
        migrations.AddField(
            model_name='objednavka',
            name='produkt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produkt', verbose_name='Produkt'),
        ),
        migrations.CreateModel(
            name='Kontrakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zakaznik', models.CharField(max_length=100, verbose_name='Zákazník')),
                ('cislo_kontraktu', models.CharField(max_length=50, unique=True, verbose_name='Číslo kontraktu')),
                ('pocet_kusov_celkovo', models.PositiveIntegerField(verbose_name='Celkový počet kusov')),
                ('zostavajuce_mnozstvo', models.PositiveIntegerField(blank=True, verbose_name='Zostáva dodať')),
                ('datum_od', models.DateField(verbose_name='Platnosť OD')),
                ('datum_do', models.DateField(verbose_name='Platnosť DO')),
                ('je_skladom', models.BooleanField(default=False, verbose_name='Je tovar skladom?')),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produkt', verbose_name='Produkt (Diel + Index)')),
            ],
        ),
        migrations.CreateModel(
            name='Operacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poradie', models.IntegerField(default=1, verbose_name='Poradie operácie')),
                ('nazov_operacie', models.CharField(max_length=100, verbose_name='Názov (napr. Hrubovanie)')),
                ('cas_pripravy', models.IntegerField(default=0, verbose_name='Čas prípravy (min)')),
                ('cas_kus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Čas na kus (min)')),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacie', to='core.produkt')),
                ('stroj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.stroj', verbose_name='Stroj')),
            ],
            options={
                'verbose_name': 'Operácia',
                'verbose_name_plural': 'Operácie',
                'ordering': ['poradie'],
            },
        ),
        migrations.CreateModel(
            name='VyrobnyZaznam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cas_zaznamu', models.DateTimeField(auto_now_add=True)),
                ('typ_udalosti', models.CharField(choices=[('START', '🟢 Začiatok práce'), ('PAUZA', '🟠 Pauza'), ('STOP', '🔴 Koniec práce')], max_length=10)),
                ('dovod_pauzy', models.TextField(blank=True, null=True, verbose_name='Dôvod pauzy')),
                ('objednavka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zaznamy', to='core.objednavka')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Operátor')),
            ],
        ),
    ]
