# Generated by Django 5.2.10 on 2026-01-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hlasenievyroby',
            name='fotka_problemu',
            field=models.ImageField(blank=True, null=True, upload_to='hlasenia/', verbose_name='Fotka problému'),
        ),
    ]
