# Generated by Django 5.2.10 on 2026-01-29 21:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hlasenievyroby_fotka_problemu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=200, verbose_name='Názov materiálu')),
                ('kod', models.CharField(max_length=50, unique=True, verbose_name='Kód materiálu')),
                ('typ', models.CharField(choices=[('SUROVINA', 'Surovina (tyč, plech...)'), ('POLOTOVAR', 'Polotovar'), ('KOMPONENT', 'Komponent')], default='SUROVINA', max_length=20)),
                ('aktualna_zasoba', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Aktuálna zásoba')),
                ('jednotka', models.CharField(default='kg', max_length=20, verbose_name='Jednotka')),
                ('minimalna_zasoba', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Minimálna zásoba')),
                ('cena_za_jednotku', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cena za jednotku (€)')),
            ],
            options={
                'verbose_name': 'Materiál',
                'verbose_name_plural': 'Materiály',
            },
        ),
        migrations.AlterModelOptions(
            name='stroj',
            options={'verbose_name': 'Stroj', 'verbose_name_plural': 'Stroje'},
        ),
        migrations.AlterModelOptions(
            name='vyrobnyzaznam',
            options={'ordering': ['-cas_zaznamu']},
        ),
        migrations.AddField(
            model_name='objednavka',
            name='vyrobene_mnozstvo',
            field=models.IntegerField(default=0, verbose_name='Vyrobené množstvo (ks)'),
        ),
        migrations.AddField(
            model_name='vyrobnyzaznam',
            name='operacia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operacia', verbose_name='Operácia'),
        ),
        migrations.AlterField(
            model_name='kontrakt',
            name='produkt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produkt', verbose_name='Produkt'),
        ),
        migrations.AlterField(
            model_name='kontrolakvality',
            name='poznamka',
            field=models.TextField(blank=True, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='operacia',
            name='nazov_operacie',
            field=models.CharField(max_length=100, verbose_name='Názov'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='material',
            field=models.CharField(blank=True, max_length=100, verbose_name='Materiál'),
        ),
        migrations.CreateModel(
            name='KontrolnyParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=100, verbose_name='Názov parametra')),
                ('hodnota_nominalna', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Nominálna hodnota')),
                ('tolerancia_plus', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Tolerancia +')),
                ('tolerancia_minus', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Tolerancia -')),
                ('jednotka', models.CharField(default='mm', max_length=20, verbose_name='Jednotka')),
                ('poradie', models.IntegerField(default=1, verbose_name='Poradie')),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontrolne_parametre', to='core.produkt')),
            ],
            options={
                'verbose_name': 'Kontrolný parameter',
                'verbose_name_plural': 'Kontrolné parametre',
                'ordering': ['poradie'],
            },
        ),
        migrations.CreateModel(
            name='MeraniePriKontrole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namerana_hodnota', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Nameraná hodnota')),
                ('kontrola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merania', to='core.kontrolakvality')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.kontrolnyparameter')),
            ],
            options={
                'verbose_name': 'Meranie pri kontrole',
                'verbose_name_plural': 'Merania pri kontrole',
            },
        ),
        migrations.CreateModel(
            name='PrijemkaNaSklad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnozstvo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Množstvo')),
                ('datum', models.DateTimeField(default=django.utils.timezone.now)),
                ('dodavatel', models.CharField(blank=True, max_length=200, verbose_name='Dodávateľ')),
                ('cislo_dodaciho_listu', models.CharField(blank=True, max_length=100, verbose_name='Číslo dodacieho listu')),
                ('poznamka', models.TextField(blank=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.material')),
            ],
            options={
                'verbose_name': 'Príjemka na sklad',
                'verbose_name_plural': 'Príjemky na sklad',
                'ordering': ['-datum'],
            },
        ),
        migrations.CreateModel(
            name='VydajkaZoSkladu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnozstvo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Množstvo')),
                ('datum', models.DateTimeField(default=django.utils.timezone.now)),
                ('poznamka', models.TextField(blank=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.material')),
                ('objednavka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vydajky', to='core.objednavka')),
                ('operacia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operacia')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Výdajka zo skladu',
                'verbose_name_plural': 'Výdajky zo skladu',
                'ordering': ['-datum'],
            },
        ),
    ]
