# Generated by Django 5.2.10 on 2026-01-31 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_material_alter_stroj_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprievodka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_vytvorenia', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='sprievodky/', verbose_name='PDF Sprievodka')),
                ('qr_kod', models.ImageField(blank=True, null=True, upload_to='qr_kody/', verbose_name='QR kód')),
                ('podpis_operator_1', models.CharField(blank=True, max_length=100, verbose_name='Operátor 1')),
                ('podpis_operator_2', models.CharField(blank=True, max_length=100, verbose_name='Operátor 2')),
                ('podpis_operator_3', models.CharField(blank=True, max_length=100, verbose_name='Operátor 3')),
                ('objednavka', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sprievodka', to='core.objednavka')),
            ],
            options={
                'verbose_name': 'Sprievodka',
                'verbose_name_plural': 'Sprievodky',
            },
        ),
    ]
