# Generated by Django 5.2.10 on 2026-02-01 18:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sprievodka'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kontrakt',
            options={'verbose_name': 'Kontrakt', 'verbose_name_plural': 'Kontrakty'},
        ),
        migrations.CreateModel(
            name='VyrobnaDavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo_davky', models.CharField(max_length=50, unique=True, verbose_name='Číslo výrobnej dávky')),
                ('mnozstvo_davky', models.PositiveIntegerField(verbose_name='Množstvo v dávke (ks)')),
                ('datum_vytvorenia', models.DateField(default=django.utils.timezone.now, verbose_name='Dátum vytvorenia')),
                ('pozadovany_termin', models.DateField(verbose_name='Požadovaný termín dodania')),
                ('stav', models.CharField(choices=[('planovana', '📋 Plánovaná'), ('vo_vyrobe', '⚙️ Vo výrobe'), ('hotova', '✅ Hotová'), ('expedovana', '📦 Expedovaná')], default='planovana', max_length=20, verbose_name='Stav dávky')),
                ('poznamka', models.TextField(blank=True, verbose_name='Poznámka')),
                ('kontrakt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vyrobne_davky', to='core.kontrakt')),
                ('objednavka', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vyrobna_davka', to='core.objednavka', verbose_name='Vytvorená objednávka')),
            ],
            options={
                'verbose_name': 'Výrobná dávka',
                'verbose_name_plural': 'Výrobné dávky',
                'ordering': ['-datum_vytvorenia'],
            },
        ),
    ]
