# Generated by Django 5.2.10 on 2026-02-01 19:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_kontrakt_options_vyrobnadavka'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkladHotovychDielov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnozstvo', models.PositiveIntegerField(default=0, verbose_name='Množstvo na sklade (ks)')),
                ('minimalna_zasoba', models.PositiveIntegerField(default=0, verbose_name='Minimálna zásoba (ks)')),
                ('optimalna_zasoba', models.PositiveIntegerField(default=100, verbose_name='Optimálna zásoba (ks)')),
                ('datum_poslednej_prijemky', models.DateTimeField(blank=True, null=True, verbose_name='Posledná príjemka')),
                ('datum_poslednej_vydajky', models.DateTimeField(blank=True, null=True, verbose_name='Posledná výdajka')),
                ('poznamka', models.TextField(blank=True, verbose_name='Poznámka')),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produkt', verbose_name='Produkt')),
            ],
            options={
                'verbose_name': 'Sklad hotových dielov',
                'verbose_name_plural': 'Sklad hotových dielov',
                'ordering': ['produkt__nazov'],
            },
        ),
        migrations.CreateModel(
            name='PrijemkaHotovychDielov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnozstvo', models.PositiveIntegerField(verbose_name='Naskladnené množstvo (ks)')),
                ('datum', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dátum príjemky')),
                ('poznamka', models.TextField(blank=True, verbose_name='Poznámka')),
                ('objednavka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.objednavka', verbose_name='Objednávka')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Operátor')),
                ('sklad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prijemky', to='core.skladhotovychdielov')),
            ],
            options={
                'verbose_name': 'Príjemka hotových dielov',
                'verbose_name_plural': 'Príjemky hotových dielov',
                'ordering': ['-datum'],
            },
        ),
        migrations.CreateModel(
            name='VydajkaHotovychDielov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zakaznik', models.CharField(max_length=100, verbose_name='Zákazník')),
                ('mnozstvo', models.PositiveIntegerField(verbose_name='Vydané množstvo (ks)')),
                ('datum', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dátum výdajky')),
                ('cislo_dodacieho_listu', models.CharField(blank=True, max_length=100, verbose_name='Číslo dodacieho listu')),
                ('poznamka', models.TextField(blank=True, verbose_name='Poznámka')),
                ('kontrakt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.kontrakt', verbose_name='Kontrakt')),
                ('objednavka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.objednavka', verbose_name='Objednávka')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Operátor')),
                ('sklad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vydajky', to='core.skladhotovychdielov')),
                ('vyrobna_davka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vyrobnadavka', verbose_name='Výrobná dávka')),
            ],
            options={
                'verbose_name': 'Výdajka hotových dielov',
                'verbose_name_plural': 'Výdajky hotových dielov',
                'ordering': ['-datum'],
            },
        ),
    ]
