# Generated by Django 5.2.10 on 2026-02-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_skladhotovychdielov_prijemkahotovychdielov_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stroj',
            name='servis_interval_dni',
            field=models.PositiveIntegerField(default=180, help_text='Každých koľko dní je potrebný servis', verbose_name='Interval servisu (dni)'),
        ),
    ]
