# Generated by Django 5.2.10 on 2026-02-10 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_stroj_servis_interval_dni'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperaciaVyroby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poradie', models.IntegerField(verbose_name='Poradie')),
                ('nazov_operacie', models.CharField(max_length=100, verbose_name='Názov operácie')),
                ('cas_pripravy', models.IntegerField(verbose_name='Čas prípravy (min)')),
                ('cas_kus', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Čas na kus (min)')),
                ('cas_realny', models.IntegerField(blank=True, null=True, verbose_name='Reálny čas (min)')),
                ('stav', models.CharField(choices=[('caka', '⏳ Čaká'), ('vyroba', '⚙️ V práci'), ('hotova', '✅ Hotová'), ('pozastavena', '⏸️ Pozastavená')], default='caka', max_length=20, verbose_name='Stav operácie')),
                ('datum_zaciatku', models.DateTimeField(blank=True, null=True, verbose_name='Začiatok práce')),
                ('datum_ukoncenia', models.DateTimeField(blank=True, null=True, verbose_name='Koniec práce')),
                ('vyrobene_kusy', models.IntegerField(default=0, verbose_name='Vyrobené kusy')),
                ('nepodarky', models.IntegerField(default=0, verbose_name='Nepodarky')),
                ('poznamka', models.TextField(blank=True, verbose_name='Poznámka')),
                ('objednavka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacie', to='core.objednavka', verbose_name='Objednávka')),
                ('operacia_sablona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.operacia', verbose_name='Operácia (šablóna)')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Priradený operátor')),
                ('stroj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.stroj', verbose_name='Stroj')),
                ('vyrobna_davka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operacie', to='core.vyrobnadavka', verbose_name='Výrobná dávka')),
            ],
            options={
                'verbose_name': 'Operácia výroby',
                'verbose_name_plural': 'Operácie výroby',
                'ordering': ['poradie'],
            },
        ),
    ]
