# Generated by Django 5.2.10 on 2026-02-14 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_operaciavyroby'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operaciavyroby',
            name='kusy_na_vstupe',
            field=models.IntegerField(default=0, verbose_name='Kusy na vstupe (z predch. operácie)'),
        ),
        migrations.AddField(
            model_name='operaciavyroby',
            name='kusy_na_vystupe',
            field=models.IntegerField(default=0, verbose_name='Kusy na výstupe (pre ďalšiu operáciu)'),
        ),
        migrations.AlterField(
            model_name='operaciavyroby',
            name='nepodarky',
            field=models.IntegerField(default=0, verbose_name='Nepodarky (NOK)'),
        ),
        migrations.AlterField(
            model_name='operaciavyroby',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Hlavný operátor'),
        ),
        migrations.AlterField(
            model_name='operaciavyroby',
            name='vyrobene_kusy',
            field=models.IntegerField(default=0, verbose_name='Vyrobené kusy (OK)'),
        ),
        migrations.CreateModel(
            name='OperatorNaOperacii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cas_zaciatku', models.DateTimeField(verbose_name='Začiatok práce')),
                ('cas_konca', models.DateTimeField(blank=True, null=True, verbose_name='Koniec práce')),
                ('vyrobene_kusy', models.IntegerField(default=0, verbose_name='Vyrobené kusy týmto operátorom')),
                ('operacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operatori', to='core.operaciavyroby')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Operátor')),
            ],
            options={
                'verbose_name': 'Operátor na operácii',
                'verbose_name_plural': 'Operátori na operáciách',
            },
        ),
    ]
