# Generated by Django 5.2.10 on 2026-02-14 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_operaciavyroby_kusy_na_vstupe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vydajkazoskladu',
            name='objednavka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vydajky_material', to='core.objednavka'),
        ),
    ]
