# Generated by Django 5.2.10 on 2026-02-21 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_vydajkazoskladu_objednavka'),
    ]

    operations = [
        migrations.AddField(
            model_name='objednavka',
            name='je_prototyp',
            field=models.BooleanField(default=False, help_text='Interné vzorkovanie alebo prototypovanie', verbose_name='Je prototyp / vzorka?'),
        ),
        migrations.AddField(
            model_name='objednavka',
            name='kontrakt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objednavky', to='core.kontrakt', verbose_name='Kontrakt'),
        ),
        migrations.AddField(
            model_name='objednavka',
            name='prototyp_iteracia',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Iterácia prototypu'),
        ),
        migrations.AddField(
            model_name='objednavka',
            name='prototyp_poznamka',
            field=models.TextField(blank=True, verbose_name='Poznámka k prototypu'),
        ),
        migrations.AddField(
            model_name='objednavka',
            name='prototyp_pre_objednavku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prototypy', to='core.objednavka', verbose_name='Vzťahuje sa k objednávke'),
        ),
        migrations.AddField(
            model_name='objednavka',
            name='prototyp_zakaznik_schvalil',
            field=models.BooleanField(default=False, verbose_name='Prototyp schválený zákazníkom'),
        ),
        migrations.AddField(
            model_name='objednavka',
            name='typ',
            field=models.CharField(choices=[('standard', 'Štandardná výroba'), ('kontrakt', 'Kontraktová výroba'), ('prototyp', 'Vzorka / prototyp')], default='standard', max_length=20, verbose_name='Typ objednávky'),
        ),
    ]
