# Generated by Django 5.2.10 on 2026-02-21 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_objednavka_je_prototyp_objednavka_kontrakt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='objednavka',
            name='priradeni_operatori',
            field=models.ManyToManyField(blank=True, help_text='Operátori priradení k tejto objednávke', related_name='priradene_objednavky', to=settings.AUTH_USER_MODEL, verbose_name='Priradení operátori'),
        ),
    ]
