# Generated by Django 5.2.10 on 2026-02-23 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_objednavka_priradeni_operatori'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='kg_na_meter',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Hmotnosť (kg/m)'),
        ),
        migrations.AddField(
            model_name='material',
            name='priemer_mm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Priemer (mm)'),
        ),
        migrations.AddField(
            model_name='material',
            name='tyc_dlzka_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Dĺžka tyče (m)'),
        ),
        migrations.AddField(
            model_name='produkt',
            name='dlzka_na_kus_mm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Dĺžka na kus (mm)'),
        ),
        migrations.AddField(
            model_name='produkt',
            name='material_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produkty', to='core.material', verbose_name='Materiál (sklad)'),
        ),
    ]
