# Generated by Django 5.2.10 on 2026-03-02 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_produkt_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialAINavrh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stav', models.CharField(choices=[('DRAFT', 'Návrh'), ('APPROVED', 'Potvrdené'), ('REJECTED', 'Zamietnuté')], default='DRAFT', max_length=20, verbose_name='Stav')),
                ('query', models.CharField(max_length=300, verbose_name='Hľadaný dopyt')),
                ('source_url', models.URLField(blank=True, verbose_name='Zdrojová URL')),
                ('source_domain', models.CharField(blank=True, max_length=200, verbose_name='Zdrojová doména')),
                ('ai_model', models.CharField(blank=True, max_length=100, verbose_name='AI model')),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Dôvera')),
                ('navrh_data', models.JSONField(blank=True, default=dict, verbose_name='Návrh dát')),
                ('raw_response', models.TextField(blank=True, verbose_name='Raw AI odpoveď')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Dátum potvrdenia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizované')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_ai_navrhy_potvrdene', to=settings.AUTH_USER_MODEL, verbose_name='Potvrdil')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_ai_navrhy_vytvorene', to=settings.AUTH_USER_MODEL, verbose_name='Vytvoril')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_navrhy', to='core.material', verbose_name='Vytvorený materiál')),
            ],
            options={
                'verbose_name': 'AI návrh materiálu',
                'verbose_name_plural': 'AI návrhy materiálu',
                'ordering': ['-created_at'],
            },
        ),
    ]
